### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Bailey-24** [penn-pal-lab/lirf_public#2]
I know how to install it.

I think if I don't use robel, I didn't need to install robel, right?

And I don't know how to use the code.
```bash
(roboaware) pi@pi:~/Desktop/RL_learning/LIRF/interactive_reward_functions$ python ./src/door_locker.py 
Traceback (most recent call last):
  File "./src/door_locker.py", line 5, in <module>
    from src.env.hand_manipulation_suite.door_v0 import DoorEnvV0
ModuleNotFoundError: No module named 'src'
```

**Comment by kunh630** [comment]
Hi, thank you for your question!

Yes, you only need to install the Roboaware environment to run the door locking experiment.

Right now, this repo serves as a simulation benchmark for tasks mentioned in our paper. For details on training the task policies and IRF policies, please refer to our paper.

Let me know if you have further questions!
