### ISSUE TITLE
Cannnot load xml file

### ISSUE THREAD

**Issue by yukaariki** [penn-pal-lab/lirf_public#3]
Hi, I have problem.

Exception: Failed to load XML file: /interactive_reward_functions/src/env/hand_manipulation_suite/assets/door_xknob_adroit_extrageom.xml. mj_loadXML error: b"Error: PNG file load error 'empty input or file doesn't exist' in texture id = 1\nObject name = wood, id = 1, line = 37, column = 9"

Do you know how to solve this?

**Comment by edwhu** [comment]
Hi, can you please provide more info, like what is the command you ran? 

From the error, it seems like the mujoco XML is trying to load a PNG image, but cannot find it. Did you make sure to install the libraries?
